import type { Legend } from '../../types/legend';

export const cristianoRonaldo: Legend = {
  id: 'cristiano-ronaldo', slug: 'cristiano-ronaldo', name: 'Cristiano Ronaldo', shortName: 'Ronaldo', country: 'Portugal', era: '2002–present', sport: 'football',
  theme: { accent: '#d71935', secondary: '#f4d36a', glow: 'rgba(215,25,53,.32)', visual: 'reconstruction' },
  hero: { title: 'THE IMPOSSIBLE STANDARD', subtitle: 'How reinvention became a career strategy', archetype: 'The Reinventor', thesis: 'Every environment asked Cristiano Ronaldo to become a different footballer. Madeira made him hungry. Manchester made him dangerous. Madrid made him inevitable. Portugal made him eternal. Juventus proved the body could age while the standard refused to.', tags: ['reinvention','obsession','longevity','pressure'] },
  stats: [ { value: '5', label: "Ballon d'Or" }, { value: '900+', label: 'senior goals' }, { value: '3', label: 'major leagues dominated' }, { value: 'Portugal', label: 'national myth' } ],
  chapters: [
    { id:'madeira', title:'Madeira: the island before the empire', period:'1985–1997', tone:'origin', summary:'The story begins far from the football capitals, with a boy whose ambition was bigger than the island around him.', beats:['Family, sacrifice and separation built the emotional base.','The hunger was not cosmetic; it was survival energy.','GOAT Careers treats Madeira as the first rival: distance, doubt and limitation.']},
    { id:'sporting', title:'Sporting: the first acceleration', period:'1997–2003', tone:'rise', summary:'At Sporting, the raw winger begins to turn street instinct into professional danger.', beats:['The talent becomes visible to Portugal.','The body is still thin, but the personality is already loud.','The Manchester friendly becomes the door to a different life.']},
    { id:'ferguson', title:'Ferguson: the father of the monster', period:'2003', tone:'rise', summary:'Sir Alex Ferguson does not just sign a winger. He gives structure to a force that still does not know its final shape.', beats:['Ferguson protects him, challenges him and gives him the No. 7 shirt.','The relationship becomes mentorship, discipline and emotional shelter.','Manchester becomes the laboratory of the first reinvention.']},
    { id:'manchester-first-phase', title:'Manchester United: from theatre to weapon', period:'2003–2008', tone:'peak', summary:'This chapter tracks the whole transformation: first match, first free-kick goal, the Arsenal duel against Thierry Henry’s era, repeated battles with Ashley Cole, then the ban that triggered obsessive special training and led to the 2008 Ballon d’Or.', beats:['The first matches are electricity before efficiency.','The free kick announces that the technique is becoming a signature.','Ashley Cole becomes a personal exam: speed alone is no longer enough.','The suspension period becomes a private training arc.','By 2008, the winger is no longer a prospect; he is the best player in the world.']},
    { id:'ballon-2008', title:"Ballon d'Or: the first crown", period:'2008', tone:'peak', summary:'The first Ballon d’Or confirms that the experiment has worked: Cristiano has converted flair into end product.', beats:['Goals, trophies and individual control converge.','Manchester United becomes the stage where his global myth begins.','The standard changes: now he must defend being the best.']},
    { id:'real-madrid', title:'Real Madrid: the pressure machine', period:'2009–2014', tone:'reinvention', summary:'Madrid transforms him again. He becomes less ornamental, more direct, more numerical, more inevitable.', beats:['The Bernabéu demands history, not promise.','Mourinho, Özil, Di María and later Ancelotti sharpen the machine.','The rivalry with Messi becomes the measurement system of modern football.']},
    { id:'decima-bbc', title:'Décima and BBC: the imperial phase', period:'2014–2018', tone:'mythic', summary:'La Décima gives the story its European crown. The BBC era turns Madrid into a Champions League dynasty.', beats:['Benzema becomes the connector; Bale becomes the vertical weapon.','Marcelo gives friendship, rhythm and attacking freedom.','The bicycle kick against Buffon becomes a moment where even rival fans applaud the impossible.']},
    { id:'portugal', title:'Portugal: the country becomes the scene', period:'2004–2019', tone:'legacy', summary:'With Portugal, Ronaldo’s story moves beyond club domination and becomes national memory.', beats:['Early heartbreak makes the eventual triumph heavier.','Euro 2016 turns injury into leadership from the sideline.','The national team chapter proves his myth does not depend on one club.']},
    { id:'juventus', title:'Juventus: domination after 33', period:'2018–2021', tone:'reinvention', summary:'The Juventus era is not a decline chapter. It is the proof that a player aged 33 to 36 could still dominate a new league, collect awards, break records and redefine longevity.', beats:['Serie A MVP, AIC Footballer of the Year, Best Forward, Capocannoniere and repeated Juventus MVP honors.','101 official Juventus goals, 81 Serie A goals, 133 appearances and five team trophies.','The Atlético Madrid Champions League hat-trick becomes the signature European scene.','The Camp Nou double against Barcelona shows he could still own hostile stages.','Records include top-scorer honors in England, Spain and Italy, and 100+ league goals in three major European leagues.','The transfer also becomes a commercial event, including a major shirt-sales story around his arrival.']},
    { id:'return-manchester', title:'Return to Manchester: memory meets reality', period:'2021–2022', tone:'conflict', summary:'The return is emotional but complicated: a legend walks back into the place that made him, but the institution is no longer the same machine.', beats:['The first months bring goals and nostalgia.','The team context exposes the gap between memory and present reality.','This chapter is written as collision: myth, age, pressure and institutional instability.']},
    { id:'saudi-legacy', title:'Saudi Arabia and the afterlife of influence', period:'2023–present', tone:'legacy', summary:'The Saudi chapter extends his influence beyond Europe and opens a new commercial and sporting frontier.', beats:['The move changes the visibility of a league.','The body keeps competing while the story shifts from peak domination to global influence.','His legacy now reaches Mbappé, Haaland and Vinícius: the next generation of ambition.']}
  ],
  timeline: [
    { year:'2003', title:'The Manchester door opens', description:'Sporting to United: the raw winger enters Ferguson’s system.' },
    { year:'2008', title:'First Ballon d’Or', description:'The Manchester transformation reaches world-best status.' },
    { year:'2014', title:'La Décima', description:'Madrid and Ronaldo complete the European obsession.' },
    { year:'2016', title:'Portugal wins Europe', description:'Injury removes him from the field but not from the story.' },
    { year:'2018', title:'Juventus reinvention', description:'A third major league becomes the next test of universality.' }
  ],
  relationships: [
    { name:'Sir Alex Ferguson', role:'mentor', label:'The architect', description:'Protected the boy, challenged the winger and helped create the first complete Ronaldo.', weight:5 },
    { name:'Wayne Rooney', role:'teammate', label:'Fire and friction', description:'A brotherhood of intensity at United, marked by chemistry, conflict and winning pressure.', weight:4 },
    { name:'Ashley Cole', role:'opponent', label:'The exam', description:'The recurring duel forced Ronaldo to move from spectacle to solutions.', weight:3 },
    { name:'Karim Benzema', role:'teammate', label:'The connector', description:'His intelligence created space for Ronaldo’s most ruthless scoring version.', weight:5 },
    { name:'Marcelo', role:'friend', label:'The left-side joy', description:'Friendship and rhythm on the flank turned attacks into theatre.', weight:4 },
    { name:'Gareth Bale', role:'teammate', label:'The vertical weapon', description:'BBC gave Madrid speed, force and European brutality.', weight:3 },
    { name:'Lionel Messi', role:'rival', label:'The measure', description:'The rivalry made both careers feel like a weekly referendum on greatness.', weight:5 },
    { name:'Pepe', role:'friend', label:'The national brother', description:'A defensive warrior beside him through Portugal’s emotional chapters.', weight:3 }
  ],
  legendaryMoments: [
    { title:"First Ballon d'Or", date:'2008', context:'The United years produce the first world crown.', whyItMatters:'It validates the transformation from entertainer to finisher.' },
    { title:'Calma', date:'2012', context:'A celebration inside hostile pressure.', whyItMatters:'It turns silence into domination.' },
    { title:'La Décima', date:'2014', context:'Madrid reaches the tenth European Cup.', whyItMatters:'It connects Ronaldo to the institution’s deepest obsession.' },
    { title:'Euro 2016', date:'2016', context:'Portugal wins after Ronaldo leaves injured and leads from the sideline.', whyItMatters:'It reframes leadership beyond playing minutes.' },
    { title:'Bicycle kick vs Buffon', date:'2018', context:'A Champions League knockout goal that made Juventus fans applaud.', whyItMatters:'It is athletic imagination turned into history.' },
    { title:'Hat-trick vs Atlético Madrid', date:'2019', context:'Juventus needs a comeback; Ronaldo provides all three goals.', whyItMatters:'It is the Juventus-era proof of Champions League gravity.' },
    { title:'Hat-trick vs Spain', date:'2018', context:'World Cup stage, late free kick, national burden.', whyItMatters:'A reminder that pressure often made him more precise.' },
    { title:"Messi missed, Ronaldo didn't", context:'A contrast moment in the public rivalry narrative.', whyItMatters:'For fans, it symbolizes the cruelty and drama of comparison culture.' }
  ],
  legacy: [ { from:'Cristiano Ronaldo', to:'Kylian Mbappé', link:'The model of global ambition, body discipline and superstar self-construction.' }, { from:'Cristiano Ronaldo', to:'Haaland & Vinícius', link:'The next generation inherits the expectation that greatness must travel across competitions and eras.' } ],
  sportDNA: { sport:'football', primary:['reinvention','verticality','finishing','longevity'], style:'Football here is told as adaptation: winger, scorer, leader, global institution.', code:'Reinvention under pressure' },
  discovery: [ { slug:'michael-jordan', title:'Michael Jordan — THE STANDARD', reason:'Because both careers turn winning into a personal language.' }, { slug:'kobe-bryant', title:'Kobe Bryant — THE OBSESSION', reason:'Because Kobe inherited the obsession model and turned it into Mamba Mentality.' }, { slug:'lebron-james', title:'LeBron James — THE CHOSEN ONE', reason:'Because longevity and expectation define both myths.' } ],
  passport: { legendId:'cristiano-ronaldo', chapters:11, moments:8, relationships:8, sportsUnlocked:['football'], completionHint:'You unlocked the Reinvention path.' }
};
