import type { Legend } from '../../types/legend';
export const michaelJordan: Legend = {
  id:'michael-jordan', slug:'michael-jordan', name:'Michael Jordan', shortName:'Jordan', country:'USA', era:'1984–2003', sport:'basketball',
  theme:{accent:'#e10b18', secondary:'#f2f0e8', glow:'rgba(225,11,24,.34)', visual:'monument'},
  hero:{title:'THE STANDARD', subtitle:'How competition became a religion', archetype:'The Standard', thesis:'Michael Jordan did not simply win. He created the vocabulary people still use when they try to explain greatness, pressure and the final shot.', tags:['pressure','competition','dynasty','brand']},
  stats:[{value:'6',label:'NBA titles'},{value:'6',label:'Finals MVPs'},{value:'5',label:'MVPs'},{value:'Jordan Brand',label:'Nike empire'}],
  chapters:[
    {id:'childhood',title:'Before the standard',period:'1963–1981',tone:'origin',summary:'The myth starts with family, competition and the pain of being doubted.',beats:['Childhood becomes the emotional foundation.','The famous cut from the varsity team becomes a storytelling symbol of rejection.','Competition enters the personality early.']},
    {id:'unc',title:'North Carolina: the first shot',period:'1981–1984',tone:'rise',summary:'Dean Smith gives structure to the talent and the 1982 title shot gives the world an early preview.',beats:['UNC teaches discipline inside a system.','The freshman hits a national championship shot.','Jordan learns that pressure can be turned into ownership.']},
    {id:'draft-bulls',title:'Chicago receives a storm',period:'1984–1988',tone:'rise',summary:'The Bulls get a scorer, but the league slowly realizes it is watching a standard being built.',beats:['The rookie arrives with impossible athletic electricity.','Nike turns a player into a cultural product.','The Air Jordan line begins the sports-business empire.']},
    {id:'pistons',title:'The Pistons wall',period:'1988–1991',tone:'conflict',summary:'Detroit becomes the punishment that makes Jordan stronger.',beats:['The Jordan Rules turn physical defense into a mythic obstacle.','Failure forces strength, trust and tactical evolution.','The road to greatness passes through humiliation.']},
    {id:'phil-scottie',title:'Phil, Scottie and the triangle',period:'1989–1993',tone:'peak',summary:'Phil Jackson and Scottie Pippen transform individual greatness into a dynasty system.',beats:['Doug Collins had unleashed Jordan; Phil Jackson teaches the Bulls how to win as a unit.','Pippen becomes the essential second force.','The first three-peat creates the public image of inevitability.']},
    {id:'father-baseball-golf',title:'Loss, baseball and golf',period:'1993–1995',tone:'conflict',summary:'After his father’s death, Jordan leaves basketball, enters baseball and lives inside a strange pause in the myth. Golf remains a repeated window into his obsession and competitive personality.',beats:['Retirement is not weakness; it is grief, fatigue and escape.','Baseball becomes an act of personal loyalty and reinvention.','Golf reveals the same competitive addiction away from basketball.']},
    {id:'return-72',title:"I'm back",period:'1995–1996',tone:'mythic',summary:'The return becomes one of the most famous resets in sports history, leading into 72–10.',beats:['The first comeback is a cultural event.','The Bulls rebuild around hunger and memory.','72–10 turns return into domination.']},
    {id:'flu-last-shot',title:'Flu Game and Last Shot',period:'1997–1998',tone:'mythic',summary:'The final Bulls chapters become cinema: illness, exhaustion, Utah, one possession, one legacy.',beats:['The Flu Game becomes pain turned into performance.','The Last Shot becomes the cleanest ending basketball ever produced.','Jordan exits Chicago as a completed myth.']},
    {id:'wizards-comeback',title:'The second comeback',period:'2001–2003',tone:'legacy',summary:'Washington does not add trophies, but it adds complexity: a legend returns not as a perfect ending, but as a human still attached to competition.',beats:['The Wizards era shows the cost of never being done.','It complicates the mythology without destroying it.','The standard remains larger than the final chapter.']}
  ],
  timeline:[{year:'1982',title:'UNC title shot',description:'The first famous pressure moment.'},{year:'1984',title:'NBA and Nike',description:'A player and a business myth start together.'},{year:'1991',title:'First championship',description:'The Pistons wall finally falls.'},{year:'1996',title:'72–10',description:'The comeback turns into a historic team season.'},{year:'1998',title:'Last Shot',description:'The cleanest closing image of a dynasty.'}],
  relationships:[{name:'Dean Smith',role:'coach',label:'The teacher',description:'Built the college structure around the talent.',weight:3},{name:'Phil Jackson',role:'coach',label:'The dynasty architect',description:'Made greatness sustainable inside a system.',weight:5},{name:'Scottie Pippen',role:'teammate',label:'The essential partner',description:'The dynasty needed his defense, playmaking and sacrifice.',weight:5},{name:'Dennis Rodman',role:'teammate',label:'The chaos specialist',description:'Gave the second three-peat rebounding, edge and unpredictability.',weight:4},{name:'Detroit Pistons',role:'opponent',label:'The wall',description:'Physical punishment became the obstacle that sharpened Jordan.',weight:5},{name:'Magic Johnson & Larry Bird',role:'inspiration',label:'The previous kings',description:'Their era created the league Jordan had to take over.',weight:3},{name:'Kobe Bryant',role:'legacy',label:'The heir of obsession',description:'Kobe studied Jordan as if greatness could be reverse-engineered.',weight:5},{name:'Nike',role:'business',label:'The empire',description:'Jordan Brand transformed an athlete into a lasting cultural economy.',weight:5}],
  legendaryMoments:[{title:'The Shot',date:'1989',context:'Cleveland, elevation, release, explosion.',whyItMatters:'A playoff killer image is born.'},{title:'Dream Team',date:'1992',context:'Barcelona makes NBA greatness global.',whyItMatters:'Jordan becomes an international symbol.'},{title:'Flu Game',date:'1997',context:'Illness, exhaustion, Utah.',whyItMatters:'Pain becomes part of the standard.'},{title:'Last Shot',date:'1998',context:'Final seconds against Utah.',whyItMatters:'It is the cinematic definition of closure.'}],
  legacy:[{from:'Jordan',to:'Kobe',link:'Kobe inherits the footwork, the mentality and the obsession with mastery.'},{from:'Kobe',to:'LeBron',link:'LeBron becomes the next global measurement against the standard.'},{from:'LeBron',to:'Curry',link:'Curry changes the sport Jordan helped globalize.'}],
  sportDNA:{sport:'basketball',primary:['pressure','dynasty','clutch','commerce'],style:'Basketball is told through possessions, systems, rivalries and the mythology of the final shot.',code:'Competition as identity'},
  discovery:[{slug:'kobe-bryant',title:'Kobe Bryant — THE OBSESSION',reason:'Because Kobe is the most direct emotional descendant of Jordan.'},{slug:'lebron-james',title:'LeBron James — THE CHOSEN ONE',reason:'Because LeBron lives under the comparison Jordan created.'},{slug:'cristiano-ronaldo',title:'Cristiano Ronaldo — THE IMPOSSIBLE STANDARD',reason:'Because both turned personal standards into global brands.'}],
  passport:{legendId:'michael-jordan',chapters:9,moments:4,relationships:8,sportsUnlocked:['basketball'],completionHint:'You unlocked the Standard path.'}
};
